version: "3.3"

services:
  vmware-exporter:
    image: jnovack/vmware-exporter:latest
    restart: always
    environment:
      HOSTNAME: "vcenter.domain.tld"
      USERNAME: "username"
      PASSWORD: "hunter2"
#      PASSWORD_FILE: "/run/secrets/password"
#    secrets:
#      - password
    ports:
      - "9272:9272"

prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3030:3000"

#secrets:
#  password:
#    external: true
